fix: fix dry run CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,33 +17,123 @@ defaults:
     shell: bash
 env:
   PUB_ENVIRONMENT: bot.github
+  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 permissions: read-all
 
 jobs:
-  validate:
-    timeout-minutes: 5
+  test:
+    name: "Test"
     runs-on: ubuntu-latest
-
+    timeout-minutes: 5
+    outputs:
+      PUBLISH_DRY_RUN: ${{ steps.check_publish_dry_run.outputs.PUBLISH_DRY_RUN }}
     steps:
-      - uses: actions/checkout@v3
-      - uses: dart-lang/setup-dart@v1
+      - id: checkout
+        name: Checkout repository
+        uses: actions/checkout@v3
+      - id: setup_dart
+        name: Setup Dart SDK
+        uses: dart-lang/setup-dart@v1
         with:
           sdk: stable
-      - name: Activate melos
+      - id: setup_melos
+        name: Activate melos
         run: dart pub global activate melos
-      - name: Bootstrap melos
+      - id: dependencies
+        name: Bootstrap melos
         run: melos bs
-      - name: Validate code
+      - id: validate_code
+        name: Validate code
         run: melos run validate
-      - name: Test code
+      - id: test
+        name: Test code
         run: melos run test
-      - name: Activate coverage
+      - id: setup_coverage
+        name: Activate coverage
         run: dart pub global activate coverage
-      - name: Run coverage
+      - id: coverage
+        name: Run coverage
         run: melos run lcov
-      - name: Upload Coverage
+      - id: upload_coverage
+        name: Upload Coverage
         if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_call' && inputs.upload_coverage == true) }}
         uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           files: packages/*/coverage/lcov.info
+      - id: check_publish_dry_run
+        name: Check if should run publish dry run
+        run: |
+          set -e
+          if [[ ! $BRANCH_NAME =~ ^release/(v|${{ matrix.package }}/v) ]]; then
+            echo "PUBLISH_DRY_RUN=0" >> $GITHUB_ENV
+          else
+            echo "PUBLISH_DRY_RUN=1" >> $GITHUB_ENV
+          fi
+  publish_dry_run:
+    name: "Publish [DRY RUN]"
+    needs: test
+    runs-on: ubuntu-latest
+    env:
+      SHOULD_RUN: ${{ needs.test.outputs.PUBLISH_DRY_RUN }}
+    if: ${{ startsWith(github.head_ref || github.ref_name, 'release/') && needs.test.outputs.PUBLISH_DRY_RUN == 1 }}
+    strategy:
+      matrix:
+        package: [ envied, envied_generator ]
+      fail-fast: true
+      max-parallel: 1
+    steps:
+      - id: checkout
+        name: Checkout repository
+        if: ${{ env.SHOULD_RUN == 1 }}
+        uses: actions/checkout@v3
+      - id: setup_dart
+        name: Setup Dart SDK
+        if: ${{ env.SHOULD_RUN == 1 }}
+        uses: dart-lang/setup-dart@v1
+        with:
+          sdk: stable
+      - id: read_version_from_pubspec
+        name: Read version from pubspec.yaml
+        if: ${{ env.SHOULD_RUN == 1 }}
+        working-directory: packages/${{ matrix.package }}
+        run: |
+          set -e
+          VERSION=$(yq -r '.version' pubspec.yaml)
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - id: check_changelog
+        name: Check CHANGELOG.md
+        if: ${{ env.SHOULD_RUN == 1 }}
+        working-directory: packages/${{ matrix.package }}
+        run: |
+          set -e
+          if ! grep -q "## $VERSION" CHANGELOG.md; then
+            echo "CHANGELOG.md does not contain a section for $VERSION"
+            exit 1
+          fi
+      - id: validate_pub_dev_topics
+        name: Validate pub.dev topics
+        if: ${{ env.SHOULD_RUN == 1 }}
+        working-directory: packages/${{ matrix.package }}
+        run: |
+          set -e
+          pattern="^[a-z][a-z0-9-]*[a-z0-9]$"
+          for topic in $(yq -r '.topics[]' pubspec.yaml); do
+            if [[ ! $topic =~ $pattern ]]; then
+              echo "Invalid topic: $topic"
+              exit 1
+            fi
+          done
+      - id: melos
+        name: Activate melos
+        if: ${{ env.SHOULD_RUN == 1 }}
+        run: dart pub global activate melos
+      - id: dependencies
+        name: Bootstrap melos
+        if: ${{ env.SHOULD_RUN == 1 }}
+        run: melos bs
+      - id: publish_dry_run
+        name: Publish (dry run)
+        if: ${{ env.SHOULD_RUN == 1 }}
+        working-directory: packages/${{ matrix.package }}
+        run: dart pub publish --dry-run
